M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date sáb 02 abr 2022 08:51:43
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-02T08:51:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X0.0Y0.0
X0.0Y-0.2
X0.1Y0.0
X0.1Y-0.2
T0
M30
